export const EDUCATION_OPTIONS = [
  "High School",
  "Diploma",
  "Bachelor's Degree",
  "Master's Degree",
  "MBA",
  "PhD",
  "Medical Degree",
  "Law Degree",
  "Chartered Accountant",
  "Professional Degree",
  "Other",
] as const

export const PROFESSION_OPTIONS = [
  "Software Engineer",
  "Data Scientist",
  "Product Manager",
  "Business Analyst",
  "Consultant",
  "Doctor",
  "Engineer",
  "Teacher",
  "Professor",
  "Lawyer",
  "Accountant",
  "Architect",
  "Designer",
  "Marketing Manager",
  "Sales Manager",
  "HR Manager",
  "Operations Manager",
  "Financial Analyst",
  "Investment Banker",
  "Entrepreneur",
  "Business Owner",
  "Nurse",
  "Pharmacist",
  "Dentist",
  "Scientist",
  "Researcher",
  "Journalist",
  "Writer",
  "Artist",
  "Chef",
  "Pilot",
  "Civil Servant",
  "Government Employee",
  "Student",
  "Homemaker",
  "Retired",
  "Other",
] as const

export const INCOME_OPTIONS = [
  "Prefer not to say",
  "Student / Not working",
  "Below 3 LPA",
  "3-5 LPA",
  "5-10 LPA",
  "10-15 LPA",
  "15-25 LPA",
  "25-50 LPA",
  "50 LPA-1 Cr",
  "1 Cr+",
  "Other",
] as const

export const COMPLEXION_OPTIONS = ["Fair", "Wheatish", "Dusky", "Dark"] as const

export const BODY_TYPE_OPTIONS = ["Slim", "Athletic", "Average", "Plus-size"] as const

export const DIET_OPTIONS = [
  "Vegetarian",
  "Eggetarian",
  "Non-vegetarian",
  "Pescatarian",
  "Vegan",
  "Jain",
  "Other",
] as const

export const MARITAL_STATUS_OPTIONS = ["Never Married", "Divorced", "Widowed", "Annulled", "Separated"] as const

export const FAMILY_TYPE_OPTIONS = ["Joint", "Nuclear", "Extended", "Single Parent"] as const

export const FAMILY_VALUES_OPTIONS = ["Traditional", "Moderate", "Modern", "Progressive"] as const

export const SIBLINGS_MARRIED_OPTIONS = ["None", "Some", "All", "Mostly Married", "Mostly Single"] as const

export const RELIGION_OPTIONS = [
  "Hindu",
  "Muslim",
  "Christian",
  "Sikh",
  "Buddhist",
  "Jain",
  "Jewish",
  "Zoroastrian / Parsi",
  "Bahai",
  "Taoist",
  "Confucian",
  "Shinto",
  "Druze",
  "Yazidi",
  "Rastafari",
  "Cao Dai",
  "Tenrikyo",
  "Unitarian Universalist",
  "Indigenous / Tribal",
  "Pagan / Wiccan",
  "Atheist",
  "Agnostic",
  "No Religion",
  "Spiritual",
  "Other",
] as const

export const MOTHER_TONGUE_OPTIONS = [
  "Hindi",
  "English",
  "Bengali",
  "Telugu",
  "Marathi",
  "Tamil",
  "Gujarati",
  "Urdu",
  "Kannada",
  "Odia",
  "Malayalam",
  "Punjabi",
  "Assamese",
  "Sanskrit",
  "Kashmiri",
  "Sindhi",
  "Konkani",
  "Manipuri",
  "Nepali",
  "Bodo",
  "Santhali",
  "Maithili",
  "Dogri",
  "Other",
] as const

export const COMMUNITY_OPTIONS = [
  "Open to all",
  "Prefer not to say",
  "Brahmin",
  "Iyer",
  "Iyengar",
  "Namboodiri",
  "Gaur Brahmin",
  "Saraswat Brahmin",
  "Kanyakubj Brahmin",
  "Maithil Brahmin",
  "Bhumihar",
  "Kshatriya",
  "Rajput",
  "Thakur",
  "Vaishya",
  "Bania",
  "Agarwal",
  "Gupta",
  "Maheshwari",
  "Oswal",
  "Khandelwal",
  "Kayastha",
  "Jat",
  "Yadav",
  "Kurmi",
  "Gujjar",
  "Maratha",
  "Patel / Patidar",
  "Reddy",
  "Kamma",
  "Kapu",
  "Nair",
  "Ezhava",
  "Lingayat",
  "Vokkaliga",
  "Chettiar",
  "Mudaliar",
  "Pillai",
  "Gounder",
  "Scheduled Caste",
  "Scheduled Tribe",
  "OBC",
  "Jain",
  "Digambar",
  "Shwetambar",
  "Sthanakvasi",
  "Terapanthi",
  "Oswal Jain",
  "Porwal Jain",
  "Agarwal Jain",
  "Muslim",
  "Sunni",
  "Shia",
  "Ismaili",
  "Ahmadiyya",
  "Sufi",
  "Hanafi",
  "Shafi'i",
  "Syed / Sayyid",
  "Sheikh",
  "Pathan / Pashtun",
  "Mughal",
  "Memon",
  "Bohra",
  "Khoja",
  "Ansari",
  "Qureshi",
  "Malik",
  "Christian",
  "Catholic",
  "Roman Catholic",
  "Latin Catholic",
  "Syrian Christian",
  "Jacobite",
  "Marthoma",
  "Knanaya",
  "Protestant",
  "Orthodox",
  "Pentecostal",
  "Evangelical",
  "Anglican",
  "Baptist",
  "Methodist",
  "Lutheran",
  "Presbyterian",
  "CSI",
  "CNI",
  "Seventh-day Adventist",
  "Sikh",
  "Jat Sikh",
  "Khatri Sikh",
  "Arora Sikh",
  "Ramgarhia",
  "Ramdasia",
  "Mazhabi Sikh",
  "Labana",
  "Saini Sikh",
  "Kamboj Sikh",
  "Gursikh",
  "Amritdhari",
  "Buddhist",
  "Theravada",
  "Mahayana",
  "Vajrayana",
  "Navayana",
  "Tibetan Buddhist",
  "Zen",
  "Pure Land",
  "Nichiren",
  "Jewish",
  "Ashkenazi",
  "Sephardi",
  "Mizrahi",
  "Orthodox Jewish",
  "Conservative Jewish",
  "Reform Jewish",
  "Zoroastrian",
  "Parsi",
  "Irani",
  "Other",
] as const

export const RELIGION_COMMUNITY_OPTIONS: Record<string, readonly string[]> = {
  Hindu: [
    "Open to all",
    "Prefer not to say",
    "Brahmin",
    "Iyer",
    "Iyengar",
    "Namboodiri",
    "Gaur Brahmin",
    "Saraswat Brahmin",
    "Kanyakubj Brahmin",
    "Maithil Brahmin",
    "Bhumihar",
    "Kshatriya",
    "Rajput",
    "Thakur",
    "Vaishya",
    "Bania",
    "Agarwal",
    "Gupta",
    "Maheshwari",
    "Oswal",
    "Khandelwal",
    "Kayastha",
    "Jat",
    "Yadav",
    "Kurmi",
    "Gujjar",
    "Maratha",
    "Patel / Patidar",
    "Reddy",
    "Kamma",
    "Kapu",
    "Nair",
    "Ezhava",
    "Lingayat",
    "Vokkaliga",
    "Chettiar",
    "Mudaliar",
    "Pillai",
    "Gounder",
    "Scheduled Caste",
    "Scheduled Tribe",
    "OBC",
    "Other",
  ],
  Muslim: [
    "Open to all",
    "Prefer not to say",
    "Sunni",
    "Shia",
    "Ismaili",
    "Ahmadiyya",
    "Sufi",
    "Hanafi",
    "Shafi'i",
    "Syed / Sayyid",
    "Sheikh",
    "Pathan / Pashtun",
    "Mughal",
    "Memon",
    "Bohra",
    "Khoja",
    "Ansari",
    "Qureshi",
    "Malik",
    "Other",
  ],
  Christian: [
    "Open to all",
    "Prefer not to say",
    "Catholic",
    "Roman Catholic",
    "Latin Catholic",
    "Syrian Christian",
    "Jacobite",
    "Marthoma",
    "Knanaya",
    "Protestant",
    "Orthodox",
    "Pentecostal",
    "Evangelical",
    "Anglican",
    "Baptist",
    "Methodist",
    "Lutheran",
    "Presbyterian",
    "CSI",
    "CNI",
    "Seventh-day Adventist",
    "Other",
  ],
  Sikh: [
    "Open to all",
    "Prefer not to say",
    "Jat Sikh",
    "Khatri Sikh",
    "Arora Sikh",
    "Ramgarhia",
    "Ramdasia",
    "Mazhabi Sikh",
    "Labana",
    "Saini Sikh",
    "Kamboj Sikh",
    "Gursikh",
    "Amritdhari",
    "Other",
  ],
  Buddhist: [
    "Open to all",
    "Prefer not to say",
    "Theravada",
    "Mahayana",
    "Vajrayana",
    "Navayana",
    "Tibetan Buddhist",
    "Zen",
    "Pure Land",
    "Nichiren",
    "Other",
  ],
  Jain: [
    "Open to all",
    "Prefer not to say",
    "Digambar",
    "Shwetambar",
    "Sthanakvasi",
    "Terapanthi",
    "Oswal Jain",
    "Porwal Jain",
    "Agarwal Jain",
    "Other",
  ],
  Jewish: [
    "Open to all",
    "Prefer not to say",
    "Ashkenazi",
    "Sephardi",
    "Mizrahi",
    "Orthodox Jewish",
    "Conservative Jewish",
    "Reform Jewish",
    "Reconstructionist Jewish",
    "Other",
  ],
  "Zoroastrian / Parsi": ["Open to all", "Prefer not to say", "Parsi", "Irani", "Other"],
  Bahai: ["Open to all", "Prefer not to say", "Bahai", "Other"],
  Taoist: ["Open to all", "Prefer not to say", "Quanzhen", "Zhengyi", "Other"],
  Confucian: ["Open to all", "Prefer not to say", "Confucian", "Other"],
  Shinto: ["Open to all", "Prefer not to say", "Jinja Shinto", "Folk Shinto", "Other"],
  Druze: ["Open to all", "Prefer not to say", "Druze", "Other"],
  Yazidi: ["Open to all", "Prefer not to say", "Yazidi", "Other"],
  Rastafari: ["Open to all", "Prefer not to say", "Rastafari", "Other"],
  "Cao Dai": ["Open to all", "Prefer not to say", "Cao Dai", "Other"],
  Tenrikyo: ["Open to all", "Prefer not to say", "Tenrikyo", "Other"],
  "Unitarian Universalist": ["Open to all", "Prefer not to say", "Unitarian Universalist", "Other"],
  "Indigenous / Tribal": ["Open to all", "Prefer not to say", "Indigenous / Tribal community", "Other"],
  "Pagan / Wiccan": ["Open to all", "Prefer not to say", "Pagan", "Wiccan", "Other"],
  Atheist: ["Open to all", "Prefer not to say", "Atheist", "Other"],
  Agnostic: ["Open to all", "Prefer not to say", "Agnostic", "Other"],
  "No Religion": ["Open to all", "Prefer not to say", "No caste / community", "Other"],
  Spiritual: ["Open to all", "Prefer not to say", "Spiritual", "Other"],
  Other: ["Open to all", "Prefer not to say", "Other"],
}

const RELIGION_VALUE_ALIASES: Record<string, string> = {
  Hinduism: "Hindu",
  Islam: "Muslim",
  Christianity: "Christian",
  Sikhism: "Sikh",
  Buddhism: "Buddhist",
  Jainism: "Jain",
  Judaism: "Jewish",
  Zoroastrianism: "Zoroastrian / Parsi",
  "Bahai Faith": "Bahai",
  Taoism: "Taoist",
  Confucianism: "Confucian",
  Yazidism: "Yazidi",
  "Unitarian Universalism": "Unitarian Universalist",
}

export const COMMUNITY_PREFERENCE_OPTIONS = COMMUNITY_OPTIONS.filter((option) => option !== "Open to all")

export function normalizeReligionOption(religion?: string | null) {
  if (!religion) return ""
  return RELIGION_VALUE_ALIASES[religion] || religion
}

export function getCommunityOptionsForReligion(religion?: string | null) {
  if (!religion) return COMMUNITY_OPTIONS
  const normalizedReligion = normalizeReligionOption(religion)
  return RELIGION_COMMUNITY_OPTIONS[normalizedReligion] || ["Open to all", "Prefer not to say", "Other"]
}

export const STAR_RAASHI_OPTIONS = [
  "Not sure",
  "Aries / Mesh",
  "Taurus / Vrishabh",
  "Gemini / Mithun",
  "Cancer / Kark",
  "Leo / Singh",
  "Virgo / Kanya",
  "Libra / Tula",
  "Scorpio / Vrischik",
  "Sagittarius / Dhanu",
  "Capricorn / Makar",
  "Aquarius / Kumbh",
  "Pisces / Meen",
  "Other",
] as const

export function withoutOther(options: readonly string[]) {
  return options.filter((option) => option !== "Other")
}
